Repository Aryainguz/picwise.co, pull requests merged in 2024-10, with the labels that each got.

#18 feat: Implement dialog for 'Watch Demo' button to display YouTube video
  components/Hero.tsx
  components/WatchDemoModal.jsx
Labels: gssoc

#21 Added the Dockerfile to the root of the project
  Dockerfile
Labels: gssoc, level1

#29 added:: Metadata and SEO
  app/layout.tsx
  app/robots.ts
  app/sitemap.ts
  next-sitemap.config.js
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
Labels: gssoc, level1

#44 added:: Move to top button
  components/Footer.tsx
Labels: gssoc-ext

#30 fix: The layout shift on drawer opening in mobile-view
  components/Hero.tsx
Labels: level1, gssoc-ext

#70 File upload dialog bug fixed
  components/DropBox.tsx
Labels: gssoc-ext, level3
